/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */

package prueba;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeModel;


/**
 *
 * @author Jose Javier Bailon Ortiz
 */
public class Ftp extends javax.swing.JFrame  implements TreeSelectionListener,ActionListener{

    /** Creates new form Ftp */
    public Ftp() {
        initComponents();
        TreeModel model = new FileTreeModel(new File("C:\\"));
        localArbol.setModel(model);
        localArbol.addTreeSelectionListener(this);
        getDrives();
        localSelectorUnidad.addActionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        panelDivisor = new javax.swing.JSplitPane();
        panelLocalDivisor = new javax.swing.JSplitPane();
        panelArbol = new javax.swing.JPanel();
        localSelectorUnidad = new javax.swing.JComboBox<>();
        scrollLocalArbol = new javax.swing.JScrollPane();
        localArbol = new javax.swing.JTree();
        panelLocalArchivos = new javax.swing.JPanel();
        scrollLocalArchivos = new javax.swing.JScrollPane();
        localTabla = new javax.swing.JTable();
        localRuta = new javax.swing.JTextField();
        panelRemoto = new javax.swing.JPanel();
        scrollRemotoArchivos = new javax.swing.JScrollPane();
        remotoTabla = new javax.swing.JTable();
        remotoRuta = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        panelComandos = new javax.swing.JPanel();
        inputComando = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        scrollHistorial = new javax.swing.JScrollPane();
        historial = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        panelEstado = new javax.swing.JPanel();
        lbConectado = new javax.swing.JLabel();
        datosConexion = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        panelConexion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        panelBotonera = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDivisor.setDividerLocation(451);

        panelLocalDivisor.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos locales"));
        panelLocalDivisor.setDividerLocation(150);

        panelArbol.setLayout(new java.awt.BorderLayout(0, 5));

        localSelectorUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C:\\" }));
            panelArbol.add(localSelectorUnidad, java.awt.BorderLayout.NORTH);

            scrollLocalArbol.setViewportView(localArbol);

            panelArbol.add(scrollLocalArbol, java.awt.BorderLayout.CENTER);

            panelLocalDivisor.setLeftComponent(panelArbol);

            panelLocalArchivos.setLayout(new java.awt.BorderLayout(0, 10));

            localTabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            scrollLocalArchivos.setViewportView(localTabla);

            panelLocalArchivos.add(scrollLocalArchivos, java.awt.BorderLayout.CENTER);

            localRuta.setEditable(false);
            localRuta.setText("C:\\");
                panelLocalArchivos.add(localRuta, java.awt.BorderLayout.NORTH);

                panelLocalDivisor.setRightComponent(panelLocalArchivos);

                panelDivisor.setLeftComponent(panelLocalDivisor);

                panelRemoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos remotos"));
                panelRemoto.setLayout(new java.awt.BorderLayout(0, 10));

                remotoTabla.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                scrollRemotoArchivos.setViewportView(remotoTabla);

                panelRemoto.add(scrollRemotoArchivos, java.awt.BorderLayout.CENTER);

                remotoRuta.setText("/");
                panelRemoto.add(remotoRuta, java.awt.BorderLayout.NORTH);

                panelDivisor.setRightComponent(panelRemoto);

                javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
                panelCentral.setLayout(panelCentralLayout);
                panelCentralLayout.setHorizontalGroup(
                    panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDivisor, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                        .addContainerGap())
                );
                panelCentralLayout.setVerticalGroup(
                    panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDivisor, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addContainerGap())
                );

                getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

                panelInferior.setLayout(new java.awt.BorderLayout());

                panelComandos.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                panelComandos.setLayout(new java.awt.BorderLayout(5, 5));
                panelComandos.add(inputComando, java.awt.BorderLayout.CENTER);

                btnEnviar.setText("Enviar");
                panelComandos.add(btnEnviar, java.awt.BorderLayout.LINE_END);

                historial.setColumns(20);
                historial.setRows(5);
                scrollHistorial.setViewportView(historial);

                panelComandos.add(scrollHistorial, java.awt.BorderLayout.PAGE_START);

                jLabel5.setText("Comando:");
                panelComandos.add(jLabel5, java.awt.BorderLayout.LINE_START);

                panelInferior.add(panelComandos, java.awt.BorderLayout.CENTER);

                panelEstado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204))));
                panelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

                lbConectado.setText("Desconectado");
                panelEstado.add(lbConectado);
                panelEstado.add(datosConexion);

                panelInferior.add(panelEstado, java.awt.BorderLayout.SOUTH);

                getContentPane().add(panelInferior, java.awt.BorderLayout.SOUTH);

                panelSuperior.setLayout(new java.awt.BorderLayout());

                panelConexion.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                panelConexion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));

                jButton1.setText("Registrarse...");
                jButton1.setActionCommand("registrarse");
                jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                panelConexion.add(jButton1);

                jPanel1.setMinimumSize(new java.awt.Dimension(50, 0));
                jPanel1.setPreferredSize(new java.awt.Dimension(50, 0));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 50, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
                );

                panelConexion.add(jPanel1);

                jLabel1.setText("Host:");
                panelConexion.add(jLabel1);

                jTextField1.setMinimumSize(new java.awt.Dimension(100, 22));
                jTextField1.setPreferredSize(new java.awt.Dimension(100, 22));
                panelConexion.add(jTextField1);

                jLabel2.setText("Puerto:");
                panelConexion.add(jLabel2);

                jTextField2.setPreferredSize(new java.awt.Dimension(40, 22));
                panelConexion.add(jTextField2);

                jLabel3.setText("Usuario:");
                panelConexion.add(jLabel3);

                jTextField3.setPreferredSize(new java.awt.Dimension(100, 22));
                panelConexion.add(jTextField3);

                jLabel4.setText("Contraseña:");
                panelConexion.add(jLabel4);

                jTextField4.setPreferredSize(new java.awt.Dimension(100, 22));
                panelConexion.add(jTextField4);

                jButton2.setText("Conectar");
                panelConexion.add(jButton2);

                panelSuperior.add(panelConexion, java.awt.BorderLayout.NORTH);

                jButton3.setText("LS");
                panelBotonera.add(jButton3);

                jButton4.setText("GET");
                panelBotonera.add(jButton4);

                jButton5.setText("PUT");
                panelBotonera.add(jButton5);

                jButton6.setText("CD");
                panelBotonera.add(jButton6);

                jButton7.setText("DEL");
                panelBotonera.add(jButton7);

                jButton8.setText("MKDIR");
                panelBotonera.add(jButton8);

                jButton9.setText("RMDIR");
                panelBotonera.add(jButton9);

                panelSuperior.add(panelBotonera, java.awt.BorderLayout.CENTER);

                getContentPane().add(panelSuperior, java.awt.BorderLayout.NORTH);

                pack();
            }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           // java.util.logging.Logger.getLogger(Ftp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(Ftp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(Ftp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(Ftp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ftp().setVisible(true);
            }
        });
    }
    
    
    
    private void getDrives(){
        File[] paths;
    
        paths = File.listRoots();

        // for each pathname in pathname array
        for(File path:paths)
        {
            // prints file and directory paths
            System.out.println("Drive Name: "+path);
        }
        String[] names = new String[paths.length];
        for (int i = 0; i < paths.length; i++) {
           names[i] = paths[i].getAbsolutePath();
        }
        
        localSelectorUnidad.setModel(new DefaultComboBoxModel<String>(names));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel datosConexion;
    private javax.swing.JTextArea historial;
    private javax.swing.JTextField inputComando;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbConectado;
    private javax.swing.JTree localArbol;
    private javax.swing.JTextField localRuta;
    private javax.swing.JComboBox<String> localSelectorUnidad;
    private javax.swing.JTable localTabla;
    private javax.swing.JPanel panelArbol;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelComandos;
    private javax.swing.JPanel panelConexion;
    private javax.swing.JSplitPane panelDivisor;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelLocalArchivos;
    private javax.swing.JSplitPane panelLocalDivisor;
    private javax.swing.JPanel panelRemoto;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel remotoRuta;
    private javax.swing.JTable remotoTabla;
    private javax.swing.JScrollPane scrollHistorial;
    private javax.swing.JScrollPane scrollLocalArbol;
    private javax.swing.JScrollPane scrollLocalArchivos;
    private javax.swing.JScrollPane scrollRemotoArchivos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(TreeSelectionEvent e) {

    Archivo node = (Archivo)((JTree)e.getSource()).getLastSelectedPathComponent();
    if (node == null) {
    //since Nothing is selected.     
     return;
    }

    localRuta.setText(node.getAbsolutePath());
    }

    @Override
    public void actionPerformed(ActionEvent e) {

               
               TreeModel model = new FileTreeModel(new File((String)localSelectorUnidad.getSelectedItem()));
               localRuta.setText((String)localSelectorUnidad.getSelectedItem());
        localArbol.setModel(model);
    }

}//fin Ftp
